// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZLdkO56PTShQmEHbF8EN5MWO5KfanfDk',
    appId: '1:1041806917309:web:103c26a9dbc2b9329481d4',
    messagingSenderId: '1041806917309',
    projectId: 'crud-78800',
    authDomain: 'crud-78800.firebaseapp.com',
    storageBucket: 'crud-78800.appspot.com',
    measurementId: 'G-H0HQ0YZYQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ecPY3j5hUdNp9XQSwdKlpJKvVFecBfE',
    appId: '1:1041806917309:android:d4681c391fa36eb59481d4',
    messagingSenderId: '1041806917309',
    projectId: 'crud-78800',
    storageBucket: 'crud-78800.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRHCCT9axadeWRg9SKCFQQnF-YRDutirQ',
    appId: '1:1041806917309:ios:d6acd68e9d2b17229481d4',
    messagingSenderId: '1041806917309',
    projectId: 'crud-78800',
    storageBucket: 'crud-78800.appspot.com',
    iosClientId: '1041806917309-nqavrfqnstq1a590cq0f6l7saqol53lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.requestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRHCCT9axadeWRg9SKCFQQnF-YRDutirQ',
    appId: '1:1041806917309:ios:d6acd68e9d2b17229481d4',
    messagingSenderId: '1041806917309',
    projectId: 'crud-78800',
    storageBucket: 'crud-78800.appspot.com',
    iosClientId: '1041806917309-nqavrfqnstq1a590cq0f6l7saqol53lo.apps.googleusercontent.com',
    iosBundleId: 'com.example.requestApp',
  );
}
